### ISSUE TITLE
Search box does not work as expected (average priority)

### ISSUE THREAD

**Issue by Blake-Loveland** [loveland/landgrid-support#19]
While answering a support question, I went to our support site to search for 'measure' or 'latitude' to see what we had.

I notice that as I type, I get real time feedback on 'no results' however, i actually never see any results.

You can see below I have 'latitude' typed in correct, no message, no results, as soon as I make the search not match, I get a message about no results.

Where are the results for the properly spelled 'latitude' search? Return makes no difference.

![2020-12-17_05h35_46](https://user-images.githubusercontent.com/42970073/102477331-36600a80-402a-11eb-9486-3afdd18b0d1b.png)

![2020-12-17_05h35_57](https://user-images.githubusercontent.com/42970073/102477339-3b24be80-402a-11eb-9e7a-4c01f56a1ba8.png)

**Comment by Blake-Loveland** [comment]
![ll_support_search](https://user-images.githubusercontent.com/42970073/102477715-b5edd980-402a-11eb-81d8-443807a6c471.gif)

**Comment by hampelm** [comment]
I will fix that "no results" bug today. I will also look into plugging in a better search engine that will find the pages that have "latitude", but I may not be able to finish that second part before we break.

**Comment by Blake-Loveland** [comment]
Thanks for looking matt.

I was hoping it was easier fix, if you can just put it in where it goes priority wise. 

for sure good support site search is a priority in an ideal world, but no one visits the support site so, less critical than it feels.

When we get it polished up it will be nice to point folks there or use it ourselves too.

**Comment by Blake-Loveland** [comment]
(we need a 'please triage' tag?) that was the priority part really, like doesn't work, can it asap? no? Ok, well then there it fits in please.

does a tag like that make sense anywhere else?

?

**Comment by hampelm** [comment]
Fixed in b6fa5b5ebb2b3bc7498d6c73e9b263fdeaa23e30 (hopefully) -- search now shows "no results found" in the right situations; also finds latitude & longitude
